#!/bin/bash
cd /workspaces/KoKoroMichi
rm -f BATTLE_ENGINE_FILES.md BATTLE_ENGINE_MIGRATION.md BATTLE_ENGINE_SUMMARY.md CHECKLIST.md DEPLOY.md DEVELOPER_MODULES.md DEVELOPER_QUICKREF.md README.md README_REFACTOR.md README_SAAS.md REFACTOR_SUMMARY.md SETUP.md STORE_COMMANDS.md STORE_DELIVERY.md STORE_FILES_STATUS.md STORE_MIGRATION.md STORE_SYSTEM_COMPLETE.md replit.md
echo "All 18 .md files deleted from root"
